# SPDX-FileCopyrightText: 2025 The geany contributors.
# SPDX-License-Identifier: MPL-2.0

name: Tests

on:
    push:
        branches:
          - master
    pull_request:
        branches:
          - master

# Declare default permissions as read only.
permissions: read-all

jobs:
    FormatCheck:
        runs-on: ubuntu-latest
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
            with:
                egress-policy: audit

          - name: Checkout
            uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
            with:
                fetch-depth: 1

          - name: Install Go
            uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
            with:
                go-version-file: go.mod
                check-latest: true

          - name: FormatCheck
            run: if [ `go fmt ./... | wc -l` -gt 0 ] ; then echo "Found unformatted code" ; exit 1 ; else exit 0 ; fi

    StaticCheck:
        runs-on: ubuntu-latest
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
            with:
                egress-policy: audit

          - name: Checkout
            uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
            with:
                fetch-depth: 1

          - name: Install Go
            id: install_go
            uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
            with:
                go-version-file: go.mod
                check-latest: true

          - name: StaticCheck
            uses: dominikh/staticcheck-action@024238d2898c874f26d723e7d0ff4308c35589a2 # v1.4.0
            with:
                version: latest
                install-go: false
                cache-key: ${{ steps.install_go.output.go-version }}

    Test:
        runs-on: ubuntu-latest
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
            with:
                egress-policy: audit

          - name: Checkout
            uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
            with:
                fetch-depth: 1

          - name: Install Go
            uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
            with:
                go-version-file: go.mod
                check-latest: true

          - name: Test
            run: go tool gotestsum --junitfile junit.xml -- -race -v `go list ./...` --covermode=atomic --coverpkg=./... --coverprofile=coverage.txt

          - name: Upload test results to Codecov
            if: ${{ !cancelled() }}
            uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1.2.1
            with:
                token: ${{ secrets.CODECOV_TOKEN }}

          - name: Coverage
            run: go tool cover -func=coverage.txt

          - name: Upload coverage to Codecov
            uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
            with:
                token: ${{ secrets.CODECOV_TOKEN }}

    # This action is mainly composed of snippets of github.com/jidicula/go-fuzz-action
#    FuzzTest:
#        runs-on: ubuntu-latest
#        steps:
#          - name: Harden Runner
#            uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
#            with:
#                egress-policy: audit
#
#          - name: Checkout
#            uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
#            with:
#                fetch-depth: 1
#
#          - name: Install Go
#            uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
#            with:
#                go-version-file: go.mod
#                check-latest: true
#
#          - name: Run Fuzz Test
#            shell: bash
#            run: go test ${{ matrix.packages }} -fuzz="Fuzz" -fuzztime="30s" -fuzzminimizetime="10s"
#
#          - name: Upload fuzz failure seed corpus as run artifact
#            if: failure()
#            uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
#            with:
#                name: testdata
#                path: testdata
#
#          - run: echo "EVENT NAME IS ${{ github.event_name }}"
#            if: failure()
#            shell: bash
#
#          - name: Save PR head commit SHA
#            if: failure() && github.event_name == 'pull_request'
#            shell: bash
#            run: |
#                SHA="${{ github.event.pull_request.head.sha }}"
#                echo "SHA=$SHA" >> $GITHUB_ENV
#
#          - name: Save latest commit SHA if not PR
#            if: failure() && github.event_name != 'pull_request'
#            shell: bash
#            run: echo "SHA=${{ github.sha }}" >> $GITHUB_ENV
#
#          - name: Output message
#            if: failure()
#            shell: bash
#            run: |
#                MESSAGE='Fuzz test failed on commit ${{ env.SHA }}. To troubleshoot locally, use the [GitHub CLI](https://cli.github.com) to download the seed corpus with\n```\ngh run download ${{ github.run_id }} -n testdata\n```'
#                DEEPLINK="https://github.com/${{ github.repository }}/commit/${{ env.SHA }}"
#                echo -e "${MESSAGE/${{ env.SHA }}/$DEEPLINK}"
#                echo -e "${MESSAGE/${{ env.SHA }}/[${GITHUB_SHA:0:8}]($DEEPLINK)}" >> $GITHUB_STEP_SUMMARY
